### ISSUE TITLE
Unable to connect to Calabash server

### ISSUE THREAD

**Issue by exonintrendo** [appersonlabs/TiCalabash#24]
I may be missing a step entirely (unfortunately there is a scarcity of good examples and documentation), but I installed using ```npm install -g ticalabash```, however, when I run ```ti calabash --platform=iphone``` from my project directory, it runs through its steps, launches my simulator, and ouputs the following before bombing out:

```bash
** BUILD SUCCEEDED **

building the -cal scheme
Feature: Home Screen
  As an App Developer
  I want to see an example feature work on a default alloy app
  So that I can start using TiCalabash quickly

  Scenario: See Home Screen                          # features/home_screen.feature:6
#<RuntimeError: Timed out connecting to Calabash server after 10 retries. Make sure it is linked and App isn't crashing>
  Unable to make connection to Calabash Server at http://localhost:37265/
  Make sure you don't have a firewall blocking traffic to http://localhost:37265/.
   (RuntimeError)
  /Users/alexphillips/.rvm/gems/ruby-2.1.3/gems/calabash-cucumber-0.11.3/lib/calabash-cucumber/launcher.rb:778:in `rescue in ensure_connectivity'
  /Users/alexphillips/.rvm/gems/ruby-2.1.3/gems/calabash-cucumber-0.11.3/lib/calabash-cucumber/launcher.rb:740:in `ensure_connectivity'
  /Users/alexphillips/.rvm/gems/ruby-2.1.3/gems/calabash-cucumber-0.11.3/lib/calabash-cucumber/launcher.rb:608:in `relaunch'
  /Users/alexphillips/Documents/diesel/svn/source/wral/applications/mobile/wralnews/build/iphone/features/ios/support/01_launch.rb:29:in `Before'

Failing Scenarios:
cucumber features/home_screen.feature:6 # Scenario: See Home Screen

1 scenario (1 failed)
0 steps
5m8.931s
#<RuntimeError: Timed out connecting to Calabash server after 10 retries. Make sure it is linked and App isn't crashing>
  Unable to make connection to Calabash Server at http://localhost:37265/
  Make sure you don't have a firewall blocking traffic to http://localhost:37265/.
   (RuntimeError)
  /Users/alexphillips/.rvm/gems/ruby-2.1.3/gems/calabash-cucumber-0.11.3/lib/calabash-cucumber/launcher.rb:778:in `rescue in ensure_connectivity'
  /Users/alexphillips/.rvm/gems/ruby-2.1.3/gems/calabash-cucumber-0.11.3/lib/calabash-cucumber/launcher.rb:740:in `ensure_connectivity'
  /Users/alexphillips/.rvm/gems/ruby-2.1.3/gems/calabash-cucumber-0.11.3/lib/calabash-cucumber/launcher.rb:608:in `relaunch'
  /Users/alexphillips/Documents/diesel/svn/source/wral/applications/mobile/wralnews/build/iphone/features/ios/support/01_launch.rb:29:in `Before'
    Given I am on the Home Screen                    # features/step_definitions/ticalabash_custom_steps.rb:1
    Then I should see text containing "Hello, World" # calabash-cucumber-0.11.3/features/step_definitions/calabash_steps.rb:384
    And take picture                                 # calabash-cucumber-0.11.3/features/step_definitions/calabash_steps.rb:229

Failing Scenarios:
cucumber features/home_screen.feature:6 # Scenario: See Home Screen

1 scenario (1 failed)
3 steps (3 skipped)
5m8.258s
```

Thoughts?

**Comment by shodanuk** [comment]
This may be a Calabash-ios issue rather than a ticalabash issue.

I reported something very similar as an issue on the calabash-ios repo but unfortunately my priorities shifted and I didn't have a chance to follow up, so they closed it.

See https://github.com/calabash/calabash-ios/issues/623#event-215158445

**Comment by Sophrinix** [comment]
Is this with a default project? What about on android?

**Comment by exonintrendo** [comment]
Yes, I am able to run on a USB connected Android device.

**Comment by Sophrinix** [comment]
I know it has been a month since you have responded. Could you try it again. I just updated ticalabash. Thanks.

**Comment by exonintrendo** [comment]
@Sophrinix Going to give it a try now. Will let you know. Thanks.

**Comment by pasine** [comment]
Same problem here. The application works fine locally, but fails when I try to test it on Travis.
The error is exactly the same.

**Comment by pasine** [comment]
I checked the linked issue and I found one of the link was broken. You can find an example of (presumably) working testing app [here](https://github.com/calabash/ios-smoke-test-app).

**Comment by vilix13** [comment]
I have same issue. How I can fix it? I checked linked issue but undrestand nothing..
