### ISSUE TITLE
Problem with sudo when installing

### ISSUE THREAD

**Issue by ulizama** [appersonlabs/TiCalabash#28]
I haven't been able to install because for some reason it's not accepting my sudo password when requested in the setup process:

```
Uriels-MacBook-Pro:~ ulizama$ sudo npm install -g ticalabash
Password:
/
> ticalabash@1.4.1 postinstall /usr/local/lib/node_modules/ticalabash
> node install

Installing titanium stuff...
--- Installing Build Command(s) ---
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

WARNING: Improper use of the sudo command could lead to data loss
or the deletion of important system files. Please double-check your
typing when using sudo. Type "man sudo" for more information.

To proceed, enter your password, or type Ctrl-C to abort.

Password:
Sorry, try again.
Password:
Sorry, try again.
Password:
Sorry, try again.
sudo: 3 incorrect password attempts

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

npm ERR! ticalabash@1.4.1 postinstall: `node install`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the ticalabash@1.4.1 postinstall script.
npm ERR! This is most likely a problem with the ticalabash package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install
npm ERR! You can get their info via:
npm ERR!     npm owner ls ticalabash
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "ticalabash"
npm ERR! cwd /Users/ulizama
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by ulizama** [comment]
Fixed it with:

sudo chown -R $USER /usr/local
